### ISSUE TITLE
QWS open two programs.

### ISSUE THREAD

**Issue by shashank-0116** [parth25sareen/Quick-Workspace-Setup#3]
When adding only one file to data its opening the file two times.

**Comment by parth25sareen** [comment]
>Thank you @shashank-0116 for reporting your problem. 
>I am pleased to inform you that we have identified and fixed the bug that was causing this problem.
> It has been patched in [v1.0.1](https://github.com/parth25sareen/Quick-Workspace-Setup/releases/tag/v1.0.1)
